### ISSUE TITLE
Issue when trying to read from arduino hc-05

### ISSUE THREAD

**Issue by MichauCorp** [dmicha16/simple_serial_port#4]
hello, I will begin by saying I am quite new to cpp and coding, therefore this may not even seem like an issue to you.

i am trying to read from my device but all i get is the "warning, no delimiters found".

my code is just a while loop that reads from the port and prints it onto the console.

I don't really know what to do at this point, so I am asking you

thx in advance  :)

**Comment by dmicha16** [comment]
Hey,

I'm not sure I can help you out much as I haven't looked at this code in
about 5-6 years. But it sounds like you're missing something around your
message? Afaik delimiters are characters that the code uses to define where
a message starts and where it ends. For example, {hello world} in this one
the delimiters are {} and the code will look for a starting { one and then
take the message until it finds }. You can define the delimiters you want
to use in your message in some txt config file, if I recall correctly. It's
just that it has to be you who puts the delimiters.

I hope it helps.

David

Den lør. 11. mar. 2023 kl. 11.31 skrev MichauCorp ***@***.***

**Comment by MichauCorp** [comment]
Hello again, sorry for responding late. your response was really helpful, I simply put my message in between {} and my test program started to read it.

However now i am faced with a different problem.

The device i have connected to the program is an arduino device which acts as a sort of speedometer and will use "serial1" to send a string that will look something like this: {0.0,S} (speed and direction).

My problem is that when there are abrupt changes to the message (for example 0.0,S to 0.6,F) , there is a delay/pause in the values registering. it will take a few seconds stuck on (0.0,S) and then suddenly continue with the values changing accordingly to the current message.

My function:
int main()
{
	char com_port[] = "\\\\.\\COM6";
	DWORD COM_BAUD_RATE = CBR_115200;
	SimpleSerial Serial(com_port, COM_BAUD_RATE);

	while (true)
	{
		string str = Serial.ReadSerialPort(7,"mine");
		cout << str;
	}
}

If you have any idea as to why that happens it would be a tremendous help to me.

 Again, thx in advance.

**Comment by MichauCorp** [comment]
Update: after reviewing it for a bit, i think it may be related to buffer size, so currently i am going to try increasing it

**Comment by dmicha16** [comment]
Sure good luck, I don't think I can help you out very much without knowing
more about your setup and what you're really trying to do.

I hope you can figure it out!

Den fre. 7. apr. 2023 kl. 08.39 skrev MichauCorp ***@***.***>:
