### ISSUE TITLE
Issue with attempt to read from Arduino

### ISSUE THREAD

**Issue by Andryxa0333** [dmicha16/simple_serial_port#6]
Hello! I'm currently working on encoder with arduino. Serial monitor show everything absolutely fine. But, when I'm trying to read it's data from PC, my program just ends (with code 0), looks like that Serial.connected_ returns 0 every time. I'm starting program from Visual Studio 2019. My .cpp file, SimpleSerial.cpp and SimpleSerial.h and other files from your rep are in the same folder.
Here's my code:
`
    #include <iostream>
    #include "SimpleSerial.h"

    int main()
    {
        char com_port[] = "\\\\.\\COM7";
        DWORD COM_BAUD_RATE = CBR_9600;
        SimpleSerial Serial(com_port, COM_BAUD_RATE);
        
        if (Serial.connected_) {
            int reply_wait_time = 7;
            string syntax_type = "mine";

            string incoming = Serial.ReadSerialPort(reply_wait_time, syntax_type);
            std::cout << incoming;
        }
        bool closed_ = Serial.CloseSerialPort();
    
        if (closed_) {
            std::cout << "Bruh, I'm dead.";
        }
    }
`
Here's my Arduino code:
`
    #define A 3
    #define B 4
    #define Z 2
    
    volatile bool Flag = false;
    String my_message;
    
    void checkZ() {
      Flag = true; 
    }
    
    void setup() {
    Serial.begin(9600);
    pinMode (A, INPUT);
    pinMode (B, INPUT);
    pinMode (Z, INPUT_PULLUP);
    attachInterrupt(0, checkZ, FALLING);
    }
    
    void loop() {
      if (Flag){
        my_message = "A:"+String(digitalRead(A))+" B:"+String(digitalRead(B))+" Z:1";
      Flag = false;
      }
      else{
        my_message = "A:"+String(digitalRead(A))+" B:"+String(digitalRead(B))+" Z:0";
      }
      String complete_msg = "{" + my_message + "}"+"\n";
      char *to_send = &complete_msg[0];
      Serial.write(to_send);
    }

`
Single output from Arduino looks like this:
{A:0 B:1 Z:0}
I think, I'm doing something wrong with my PC side. If you could give any advice I would be very grateful. Thanks!

**Comment by Andryxa0333** [comment]
Looks like that issue was that while I was trying to get values to c++, at the same time my Arduino IDE was opened, so it took down the stream from com port.

**Comment by dmicha16** [comment]
Great!
